packageExtensions:
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": "*"
      "@typescript-eslint/utils": "*"
  "@angular-eslint/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/utils": "*"
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-eslint/template-parser": "*"
      eslint: "*"
      typescript: "*"
  "@angular-eslint/utils@*":
    dependencies:
      "@typescript-eslint/types": "*"
      "@typescript-eslint/utils": "*"
  "@angular/build@*":
    dependencies:
      "@angular/compiler": "*"
