#!/usr/bin/env python3
"""Deterministically validate architecture documentation."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import unicodedata
from pathlib import Path
from typing import Iterable

import yaml


ARCHITECTURE = Path("docs/architecture/architecture.md")
ARCHITECTURE_MAP = Path("docs/architecture/architecture-map.md")

ALLOWED_CHANGED_PATHS = {
    ARCHITECTURE.as_posix(),
    ARCHITECTURE_MAP.as_posix(),
}

REQUIRED_SECTIONS = (
    "Source repositories",
    "Drivers and constraints",
    "Solution context",
    "Components and responsibilities",
    "Repository ownership of components",
    "Interfaces and integrations",
    "Cross-repository relationships",
    "Data ownership",
    "Security and trust boundaries",
    "Deployment architecture",
    "Operational architecture",
    "Baseline architecture",
    "Transition architecture",
    "Target architecture",
    "Architecture decisions",
    "Contradictions",
    "Unknowns",
)

IDENTIFIER = (
    r"ARC-(?:DRV|CTX|CMP|INT|DATA|SEC|DEP|OPS|BASE|TRANS|TARGET|DEC|CON|UNK)"
    r"-[0-9]{3,}"
)

IDENTIFIER_DEFINITION = re.compile(
    rf"^#{{2,6}}\s+({IDENTIFIER})\s+[—-]\s+(.+?)\s*$"
)

SOURCE_ROW = re.compile(
    r"^\|\s*(SRC-[0-9]{3,})\s*\|\s*"
    r"([^| ]+/[^| ]+)\s*\|\s*"
    r"(primary|supporting)\s*\|\s*"
    r"([^|]+?)\s*\|\s*"
    r"([0-9a-f]{40})\s*\|$"
)

MAP_ROW = re.compile(
    rf"^\|\s*({IDENTIFIER})\s*\|\s*"
    r"([^|]+)\|\s*"
    r"([^|]+)\|\s*"
    r"([^|]*)\|\s*"
    r"\[([^\]]+)\]\(([^)]+)\)\s*\|$"
)

MARKDOWN_LINK = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
MARKDOWN_HEADING = re.compile(r"^#{1,6}\s+(.+?)\s*$")

SECRET_PATTERNS = {
    "private key": re.compile(
        r"-----BEGIN [A-Z ]*PRIVATE KEY-----"
    ),
    "GitHub legacy token": re.compile(
        r"\bgh[pousr]_[A-Za-z0-9_]{20,}\b"
    ),
    "GitHub fine-grained token": re.compile(
        r"\bgithub_pat_[A-Za-z0-9_]{20,}\b"
    ),
    "AWS access key": re.compile(
        r"\bAKIA[0-9A-Z]{16}\b"
    ),
    "Google API key": re.compile(
        r"\bAIza[0-9A-Za-z_-]{30,}\b"
    ),
}


class ValidationFailure(RuntimeError):
    """Raised for validation setup failures."""


def run_git(arguments: Iterable[str]) -> bytes:
    """Run Git without invoking a shell."""
    completed = subprocess.run(
        ["git", *arguments],
        check=False,
        capture_output=True,
    )

    if completed.returncode != 0:
        stderr = completed.stderr.decode(
            "utf-8",
            errors="replace",
        ).strip()
        raise ValidationFailure(
            f"git {' '.join(arguments)} failed: {stderr}"
        )

    return completed.stdout


def load_scope(path: Path) -> dict:
    """Load the bootstrap scope safely."""
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))

    if not isinstance(loaded, dict):
        raise ValidationFailure(
            f"{path} must contain a YAML object"
        )

    return loaded


def github_anchor(text: str) -> str:
    """
    Approximate GitHub's heading-anchor generation for repository-local checks.

    This handles the ASCII-oriented architecture headings generated by the
    supplied templates and skills.
    """
    normalized = unicodedata.normalize("NFKD", text).lower()
    kept = "".join(
        character
        for character in normalized
        if (
            character.isalnum()
            or character in (" ", "_", "-")
        )
    )
    return re.sub(r"-+", "-", re.sub(r"\s+", "-", kept.strip()))


def parse_definitions(
    architecture: str,
    errors: list[str],
) -> dict[str, dict[str, object]]:
    """Parse stable architecture identifier definitions."""
    definitions: dict[str, dict[str, object]] = {}

    for line_number, line in enumerate(
        architecture.splitlines(),
        start=1,
    ):
        match = IDENTIFIER_DEFINITION.fullmatch(line)

        if not match:
            continue

        identifier = match.group(1)
        title = match.group(2).strip()

        if identifier in definitions:
            original_line = definitions[identifier]["line"]
            errors.append(
                f"{ARCHITECTURE}: duplicate definition "
                f"{identifier} at lines {original_line} "
                f"and {line_number}"
            )
        else:
            definitions[identifier] = {
                "title": title,
                "line": line_number,
            }

    if not definitions:
        errors.append(
            f"{ARCHITECTURE}: no stable architecture "
            "identifiers found"
        )

    return definitions


def parse_source_rows(
    architecture: str,
    errors: list[str],
) -> dict[str, dict[str, str]]:
    """Parse the authoritative source-repository table."""
    sources: dict[str, dict[str, str]] = {}
    source_ids: set[str] = set()

    for line_number, line in enumerate(
        architecture.splitlines(),
        start=1,
    ):
        if not line.startswith("| SRC-"):
            continue

        match = SOURCE_ROW.fullmatch(line)

        if not match:
            errors.append(
                f"{ARCHITECTURE}: malformed source row "
                f"at line {line_number}"
            )
            continue

        source_id = match.group(1)
        repository = match.group(2)
        role = match.group(3)
        configured_ref = match.group(4).strip()
        commit = match.group(5)

        if source_id in source_ids:
            errors.append(
                f"{ARCHITECTURE}: duplicate source ID "
                f"{source_id}"
            )

        source_ids.add(source_id)

        if repository in sources:
            errors.append(
                f"{ARCHITECTURE}: duplicate source "
                f"repository {repository}"
            )

        sources[repository] = {
            "id": source_id,
            "role": role,
            "ref": configured_ref,
            "commit": commit,
        }

    return sources


def validate_sources(
    scope: dict,
    source_rows: dict[str, dict[str, str]],
    errors: list[str],
) -> None:
    """Compare architecture source rows with configured scope."""
    scope_sources = {
        source["repository"]: source
        for source in scope["sources"]
    }

    for repository in sorted(
        set(scope_sources) - set(source_rows)
    ):
        errors.append(
            f"{ARCHITECTURE}: missing configured source "
            f"{repository}"
        )

    for repository in sorted(
        set(source_rows) - set(scope_sources)
    ):
        errors.append(
            f"{ARCHITECTURE}: declares source not present "
            f"in scope: {repository}"
        )

    for repository, configured in scope_sources.items():
        if repository not in source_rows:
            continue

        declared = source_rows[repository]

        if declared["role"] != configured["role"]:
            errors.append(
                f"{ARCHITECTURE}: role mismatch for "
                f"{repository}"
            )

        if declared["ref"] != configured["ref"]:
            errors.append(
                f"{ARCHITECTURE}: configured-ref mismatch "
                f"for {repository}"
            )

        if not re.fullmatch(
            r"[0-9a-f]{40}",
            declared["commit"],
        ):
            errors.append(
                f"{ARCHITECTURE}: invalid full commit SHA "
                f"for {repository}"
            )

    primary_count = sum(
        1
        for source in source_rows.values()
        if source["role"] == "primary"
    )

    if primary_count != 1:
        errors.append(
            f"{ARCHITECTURE}: exactly one source row must "
            "have primary role"
        )


def validate_map(
    map_content: str,
    definitions: dict[str, dict[str, object]],
    errors: list[str],
) -> None:
    """Ensure the map contains only authoritative IDs and exact titles."""
    map_ids: set[str] = set()

    for line_number, line in enumerate(
        map_content.splitlines(),
        start=1,
    ):
        if not re.match(r"^\|\s*ARC-", line):
            continue

        match = MAP_ROW.fullmatch(line)

        if not match:
            errors.append(
                f"{ARCHITECTURE_MAP}: malformed map row "
                f"at line {line_number}"
            )
            continue

        identifier = match.group(1)
        title = match.group(3).strip()
        link_text = match.group(5).strip()
        link = match.group(6).strip()

        if identifier in map_ids:
            errors.append(
                f"{ARCHITECTURE_MAP}: duplicate map "
                f"identifier {identifier}"
            )

        map_ids.add(identifier)

        if identifier not in definitions:
            errors.append(
                f"{ARCHITECTURE_MAP}: {identifier} is not "
                f"defined in {ARCHITECTURE}"
            )
            continue

        if definitions[identifier]["title"] != title:
            errors.append(
                f"{ARCHITECTURE_MAP}: title for {identifier} "
                "does not exactly match authoritative title"
            )

        if not link.startswith("architecture.md#"):
            errors.append(
                f"{ARCHITECTURE_MAP}: {identifier} must "
                "link into architecture.md"
            )

        if not link_text:
            errors.append(
                f"{ARCHITECTURE_MAP}: {identifier} has "
                "empty link text"
            )

    missing_map_ids = set(definitions) - map_ids

    for identifier in sorted(missing_map_ids):
        errors.append(
            f"{ARCHITECTURE_MAP}: missing index entry "
            f"for {identifier}"
        )


def collect_anchors(path: Path) -> set[str]:
    """Collect generated anchors for a Markdown file."""
    anchors: set[str] = set()
    occurrences: dict[str, int] = {}

    for line in path.read_text(
        encoding="utf-8"
    ).splitlines():
        match = MARKDOWN_HEADING.fullmatch(line)

        if not match:
            continue

        base = github_anchor(match.group(1))
        occurrence = occurrences.get(base, 0)
        anchor = base if occurrence == 0 else f"{base}-{occurrence}"
        occurrences[base] = occurrence + 1
        anchors.add(anchor)

    return anchors


def validate_links(
    paths: Iterable[Path],
    errors: list[str],
) -> None:
    """Validate local Markdown files and anchors."""
    anchor_cache: dict[Path, set[str]] = {}

    for path in paths:
        anchor_cache[path.resolve()] = collect_anchors(path)

    for path in paths:
        content = path.read_text(encoding="utf-8")

        for raw_target in MARKDOWN_LINK.findall(content):
            target = raw_target.strip()

            if target.startswith(("https://", "http://", "mailto:")):
                continue

            file_part, separator, anchor = target.partition("#")

            if file_part:
                target_file = (
                    path.parent / file_part
                ).resolve()
            else:
                target_file = path.resolve()

            if not target_file.is_file():
                errors.append(
                    f"{path}: broken local link {target}"
                )
                continue

            if separator:
                anchors = anchor_cache.get(target_file)

                if anchors is None:
                    anchors = collect_anchors(target_file)
                    anchor_cache[target_file] = anchors

                if anchor not in anchors:
                    errors.append(
                        f"{path}: missing anchor {anchor} "
                        f"in {target_file}"
                    )


def validate_secrets(
    paths: Iterable[Path],
    errors: list[str],
) -> None:
    """Detect obvious credential material in architecture outputs."""
    for path in paths:
        content = path.read_text(encoding="utf-8")

        for name, pattern in SECRET_PATTERNS.items():
            if pattern.search(content):
                errors.append(
                    f"{path}: possible {name} detected"
                )


def changed_paths_for_base(base: str) -> set[str]:
    """Return pull-request paths relative to a base commit."""
    output = run_git(
        ["diff", "--name-only", "-z", f"{base}...HEAD"]
    )
    return {
        item.decode("utf-8")
        for item in output.split(b"\x00")
        if item
    }


def working_tree_paths() -> set[str]:
    """Return tracked and untracked working-tree paths."""
    tracked = run_git(["diff", "--name-only", "-z"])
    staged = run_git(
        ["diff", "--cached", "--name-only", "-z"]
    )
    untracked = run_git(
        ["ls-files", "--others", "--exclude-standard", "-z"]
    )

    return {
        item.decode("utf-8")
        for item in (
            tracked.split(b"\x00")
            + staged.split(b"\x00")
            + untracked.split(b"\x00")
        )
        if item
    }


def build_parser() -> argparse.ArgumentParser:
    """Build command-line arguments."""
    parser = argparse.ArgumentParser(
        description=__doc__,
    )
    parser.add_argument(
        "--scope",
        required=True,
        type=Path,
    )

    change_group = parser.add_mutually_exclusive_group()
    change_group.add_argument("--base")
    change_group.add_argument(
        "--working-tree",
        action="store_true",
    )

    return parser


def main() -> int:
    """Program entry point."""
    arguments = build_parser().parse_args()
    errors: list[str] = []

    for path in (ARCHITECTURE, ARCHITECTURE_MAP):
        if not path.is_file():
            errors.append(f"missing required file {path}")

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    try:
        architecture = ARCHITECTURE.read_text(
            encoding="utf-8"
        )
        map_content = ARCHITECTURE_MAP.read_text(
            encoding="utf-8"
        )
        scope = load_scope(arguments.scope)
    except (OSError, UnicodeError, yaml.YAMLError, ValidationFailure) as error:
        print(f"validation setup failed: {error}", file=sys.stderr)
        return 1

    authoritative_declaration = (
        "**Authority:** This file is the authoritative, "
        "human-reviewed architecture record."
    )

    if authoritative_declaration not in architecture:
        errors.append(
            f"{ARCHITECTURE}: missing authoritative declaration"
        )

    if "**Index-only declaration:**" not in map_content:
        errors.append(
            f"{ARCHITECTURE_MAP}: missing index-only declaration"
        )

    for section in REQUIRED_SECTIONS:
        section_pattern = re.compile(
            rf"^## {re.escape(section)}\s*$",
            re.MULTILINE,
        )

        if not section_pattern.search(architecture):
            errors.append(
                f"{ARCHITECTURE}: missing section "
                f"{section!r}"
            )

    definitions = parse_definitions(
        architecture,
        errors,
    )
    source_rows = parse_source_rows(
        architecture,
        errors,
    )
    validate_sources(
        scope,
        source_rows,
        errors,
    )
    validate_map(
        map_content,
        definitions,
        errors,
    )
    validate_links(
        (ARCHITECTURE, ARCHITECTURE_MAP),
        errors,
    )
    validate_secrets(
        (ARCHITECTURE, ARCHITECTURE_MAP),
        errors,
    )

    try:
        if arguments.base:
            changed_paths = changed_paths_for_base(
                arguments.base
            )
        elif arguments.working_tree:
            changed_paths = working_tree_paths()
        else:
            changed_paths = set()
    except (ValidationFailure, UnicodeDecodeError) as error:
        errors.append(str(error))
        changed_paths = set()

    for path in sorted(
        changed_paths - ALLOWED_CHANGED_PATHS
    ):
        errors.append(
            f"disallowed changed path: {path}"
        )

    if arguments.working_tree and not changed_paths:
        errors.append(
            "working tree contains no architecture changes"
        )

    if errors:
        print(
            "architecture validation failed:",
            file=sys.stderr,
        )

        for error in errors:
            print(f"  - {error}", file=sys.stderr)

        return 1

    print("architecture validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())