#
# See https://learn.microsoft.com/azure/devops/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
    batch: true
    branches:
        include:
            - main
            - release

pool:
    vmImage: "ubuntu-latest"

variables:
    - group: "CI - Build"

stages:
    - stage: build
      displayName: Build
      dependsOn: []
      jobs:
          - job: build
            displayName: Build
            variables:
                solution: "Cubido.Template.slnx"
                project: "src/Web/Web.csproj"
                buildConfiguration: "Release"
                # see https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-environment-variables
                NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
            steps:
                - task: Cache@2
                  displayName: Cache NuGet packages
                  inputs:
                      # see https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget
                      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
                      restoreKeys: |
                          nuget | "$(Agent.OS)"
                          nuget
                      path: $(NUGET_PACKAGES)
#if (IncludeFrontend)
                - task: Cache@2
                  displayName: Cache yarn packages
                  inputs:
                      key: '"yarn" | "$(Agent.OS)" | **/yarn.lock'
                      restoreKeys: |
                          yarn | "$(Agent.OS)"
                          yarn
                      path: $(YARN_CACHE_FOLDER)
                - task: NodeTool@0
                  inputs:
                      versionSpec: "24"
                  displayName: "Install Node.js"
                - script: corepack enable
                  displayName: "Enable Corepack"
                - script: yarn install
                  displayName: "Install dependencies"
                  workingDirectory: src/Frontend
                  env:
                      TELERIK_LICENSE: $(KendoLicenseKey)
                - script: yarn build --config production
                  displayName: "Build"
                  workingDirectory: src/Frontend
#endif
                - task: DotNetCoreCLI@2
                  displayName: "Restore NuGet packages"
                  inputs:
                      command: "restore"
                      projects: $(solution)
                      verbosityRestore: Minimal
                - task: DotNetCoreCLI@2
                  displayName: "dotnet build"
                  inputs:
                      command: "build"
                      arguments: "-c $(buildConfiguration) --no-restore"
                      projects: $(solution)
                - task: DotNetCoreCLI@2
                  displayName: "dotnet test"
                  inputs:
                      command: "test"
                      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
                      projects: $(solution)
                  env:
                      USE_CONTAINER: "true"
                - task: DotNetCoreCLI@2
                  displayName: "dotnet publish"
                  inputs:
                      command: publish
                      projects: $(project)
                      arguments: "-c $(buildConfiguration) -r linux-x64 --self-contained false -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true -o $(Build.ArtifactStagingDirectory)"
                      publishWebProjects: false
                      modifyOutputPath: false
                - publish: $(Build.ArtifactStagingDirectory)
                  displayName: "Publish App"
                  artifact: App

    - stage: deployDev
      displayName: Deploy to Development
      dependsOn:
          - build
      condition: succeeded()
      jobs:
          - deployment: deployToDev
            displayName: Deploy to Development Environment
            environment: "Development"
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - checkout: self
                              displayName: "Checkout source code"
                            - download: current
                              artifact: App
                              displayName: "Download Build Artifacts"

                            - task: AzureCLI@2
                              displayName: "Deploy Infrastructure"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  scriptType: "bash"
                                  scriptLocation: "inlineScript"
                                  inlineScript: |
                                      echo "Deploying Bicep file"
                                      cd Infrastructure

                                      az deployment group create \
                                        --resource-group "rg-cubido-template-dev" \
                                        --template-file main.bicep \
                                        --parameters @parameters-dev.json \
                                        --mode Incremental \
                                        --verbose

                                      echo "Bicep deployed"

                            - task: AzureWebApp@1
                              displayName: "Deploy Web Application"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  appType: "webApp"
                                  appName: "guard-web-dev"
                                  package: "$(Pipeline.Workspace)/**/*.zip"
                                  runtimeStack: "DOTNETCORE|10.0"

                            - task: AzureAppServiceManage@0
                              displayName: "Restart App Service"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  Action: "Restart Azure App Service"
                                  WebAppName: "guard-web-dev"

    - stage: deployTest
      displayName: Deploy to Testing
      dependsOn:
          - build
      condition: succeeded()
      jobs:
          - deployment: deployToTest
            displayName: Deploy to Test Environment
            environment: "Testing"
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - checkout: self
                              displayName: "Checkout source code"
                            - download: current
                              artifact: App
                              displayName: "Download Build Artifacts"

                            - task: AzureCLI@2
                              displayName: "Deploy Infrastructure"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  scriptType: "bash"
                                  scriptLocation: "inlineScript"
                                  inlineScript: |
                                      echo "Deploying Bicep file"
                                      cd Infrastructure

                                      az deployment group create \
                                        --resource-group "rg-cubido-template-test" \
                                        --template-file main.bicep \
                                        --parameters @parameters-test.json \
                                        --mode Incremental \
                                        --verbose

                                      echo "Bicep deployed"

                            - task: AzureWebApp@1
                              displayName: "Deploy Web Application"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  appType: "webApp"
                                  appName: "guard-web-test"
                                  package: "$(Pipeline.Workspace)/**/*.zip"
                                  runtimeStack: "DOTNETCORE|10.0"

                            - task: AzureAppServiceManage@0
                              displayName: "Restart App Service"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  Action: "Restart Azure App Service"
                                  WebAppName: "guard-web-test"

    - stage: deployProd
      displayName: Deploy to Production
      dependsOn:
          - build
      condition: succeeded()
      jobs:
          - deployment: deployToProd
            displayName: Deploy to Production Environment
            environment: "Production"
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - checkout: self
                              displayName: "Checkout source code"
                            - download: current
                              artifact: App
                              displayName: "Download Build Artifacts"

                            - task: AzureCLI@2
                              displayName: "Deploy Infrastructure"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  scriptType: "bash"
                                  scriptLocation: "inlineScript"
                                  inlineScript: |
                                      echo "Deploying Bicep file"
                                      cd Infrastructure

                                      az deployment group create \
                                        --resource-group "rg-cubido-template-prod" \
                                        --template-file main.bicep \
                                        --parameters @parameters-prod.json \
                                        --mode Incremental \
                                        --verbose

                                      echo "Bicep deployed"

                            - task: AzureWebApp@1
                              displayName: "Deploy Web Application"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  appType: "webApp"
                                  appName: "guard-web-prod"
                                  package: "$(Pipeline.Workspace)/**/*.zip"
                                  runtimeStack: "DOTNETCORE|10.0"

                            - task: AzureAppServiceManage@0
                              displayName: "Restart App Service"
                              inputs:
                                  azureSubscription: "Azure Service Connection"
                                  Action: "Restart Azure App Service"
                                  WebAppName: "guard-web-prod"
