trigger: none

variables:
    - group: "CI - Build"

jobs:
    - job: checkFormatting
      displayName: "Check Code Formatting"
      pool:
          vmImage: "windows-2025"
      variables:
          solution: "Cubido.Template.slnx"
          NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
      steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
                packageType: "sdk"
                version: "10.x"
          - task: Cache@2
            displayName: Cache NuGet packages
            inputs:
                # see https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget
                key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
                restoreKeys: |
                    nuget | "$(Agent.OS)"
                    nuget
                path: $(NUGET_PACKAGES)
          - task: DotNetCoreCLI@2
            displayName: "Restore NuGet packages"
            inputs:
                command: "restore"
                projects: $(solution)
                verbosityRestore: Minimal
          - task: DotNetCoreCLI@2
            displayName: "Run dotnet format"
            inputs:
                command: "custom"
                custom: "format"
                projects: src/**/*.csproj
                arguments: "--verify-no-changes --verbosity detailed"
#if (IncludeFrontend)
    - job: buildFrontend
      displayName: "Run Frontend Unit Tests"
      pool:
          vmImage: "windows-2025"
      variables:
          # see https://yarnpkg.com/configuration/yarnrc
          YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn/cache
          YARN_ENABLE_GLOBAL_CACHE: false
      steps:
          - checkout: self
            lfs: true
          - task: Cache@2
            displayName: Cache yarn packages
            inputs:
                key: '"yarn" | "$(Agent.OS)" | **/yarn.lock'
                restoreKeys: |
                    yarn | "$(Agent.OS)"
                    yarn
                path: $(YARN_CACHE_FOLDER)
          - task: NodeTool@0
            inputs:
                versionSpec: "24"
            displayName: "Install Node.js"
          - script: corepack enable
            displayName: "Enable Corepack"
          - script: yarn install
            displayName: "Install dependencies"
            workingDirectory: src/Frontend
            env:
                TELERIK_LICENSE: $(KendoLicenseKey)
          - script: yarn build
            displayName: "Build"
            workingDirectory: src/Frontend
          - script: yarn ng test --no-watch --no-progress --browsers=ChromeHeadless
            displayName: "Unit tests"
            workingDirectory: src/Frontend
            condition: false # Temporarily disabled
          - script: yarn playwright install chromium --with-deps
            displayName: "Install playwright"
            workingDirectory: src/Frontend
            condition: false # Temporarily disabled
          - script: yarn playwright test
            displayName: "Visual tests"
            workingDirectory: src/Frontend
            condition: false # Temporarily disabled
            env:
                CI: true
          - task: PublishTestResults@2
            displayName: "Publish test results"
            inputs:
                searchFolder: "src/Frontend/test-results"
                testResultsFormat: "JUnit"
                testResultsFiles: "e2e-junit-results.xml"
                mergeTestResults: true
                failTaskOnFailedTests: true
                testRunTitle: "Visual Tests"
            # condition: succeededOrFailed()
            condition: false # Temporarily disabled
          - task: PublishPipelineArtifact@1
            displayName: "Publish Playwright Report"
            inputs:
                targetPath: src/Frontend/playwright-report
                artifact: playwright-report-$(System.JobAttempt)
            # condition: succeededOrFailed()
            condition: false # Temporarily disabled
#endif

    - job: runBackendTests
      displayName: "Run Backend Unit Tests"
      pool:
          vmImage: "ubuntu-latest"
      variables:
          solution: "Cubido.Template.slnx"
          buildConfiguration: "Release"
          # see https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-environment-variables
          NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
#if (IncludeFrontend)
          # see https://yarnpkg.com/configuration/yarnrc
          YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn/cache
          YARN_ENABLE_GLOBAL_CACHE: false
#endif
      steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
                packageType: "sdk"
                version: "10.x"

#if (IncludeFrontend)
          - task: NodeTool@0
            inputs:
                versionSpec: "24"
            displayName: "Install Node.js"
          - script: corepack enable
            displayName: "Enable Corepack"

          - task: Cache@2
            displayName: Cache yarn packages
            inputs:
                key: '"yarn" | "$(Agent.OS)" | **/yarn.lock'
                restoreKeys: |
                    yarn | "$(Agent.OS)"
                    yarn
                path: $(YARN_CACHE_FOLDER)
#endif
          - task: Cache@2
            displayName: Cache NuGet packages
            inputs:
                # see https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget
                key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
                restoreKeys: |
                    nuget | "$(Agent.OS)"
                    nuget
                path: $(NUGET_PACKAGES)

#if (IncludeFrontend)
          - script: yarn install
            displayName: "Install dependencies"
            workingDirectory: src/Frontend
            env:
                TELERIK_LICENSE: $(KendoLicenseKey)
#endif
          - task: DotNetCoreCLI@2
            displayName: "Restore NuGet packages"
            inputs:
                command: "restore"
                projects: $(solution)
                verbosityRestore: Minimal
                restoreArguments: "/p:BuildWithNetFrameworkHostedCompiler=true"

          - task: DotNetCoreCLI@2
            displayName: "Build Solution"
            inputs:
                command: "build"
                projects: $(solution)
                arguments: "--configuration $(buildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: "Run Unit Tests"
            inputs:
                command: "test"
                projects: $(solution)
                arguments: '--configuration $(buildConfiguration) --collect:"Code Coverage"'
            env:
                USE_CONTAINER: "true"
