@AuthToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDQ0NyIsIm5iZiI6MTY3NzkyNTI0NywiaWF0IjoxNjc3OTI1MjQ3LCJleHAiOjE2Nzc5Mjg4NDcsImF1ZCI6IldlYlVJQVBJIiwic2NvcGUiOlsiV2ViVUlBUEkiLCJvcGVuaWQiLCJwcm9maWxlIl0sImFtciI6WyJwd2QiXSwiY2xpZW50X2lkIjoiQ2xlYW5BcmNoaXRlY3R1cmUuV2ViVUkiLCJzdWIiOiI3M2YzY2RiMC02YjRkLTRlZGEtOGYzMy03ZjFjODYyMzRiMTUiLCJhdXRoX3RpbWUiOjE2Nzc5MjUyNDQsImlkcCI6ImxvY2FsIiwic2lkIjoiOTM5REY4NzM0MzczN0E4OEQwQTREOEE2MTI0RjRDMTEiLCJqdGkiOiI0Nzg0QzFFMDNGQzlDMTFGRDkwMjEyRTMwMTVBRUQ4NSJ9.wSzL7_5cUNSCocZei-_iBulEh9PpoSsFrdeOymB7zIJ1B1sXXNS0hMMlWEJryNhcJ5wocJitUs35cYnZCDAv5ufUssztSttIG6GDAVxBbJsKVQsELPdC-FzjZx5fOCd9VXGkkykl2lcJtCQpuOuEFKR_eo6koqX4iI_kK33r10a3tCUjsZfVz3-wbLoK7imDcISNbGZosTMEZfw-BTvBIKoAn5DndgWWs0xp9LIphP2a-mczd7PKDiUriRyT1TMn_CGsyd1MUb9mvD0aV2jiPc5qRm5Rf4KKQTWKSkKv_ToTRSCWSvwV7HLOwOcY0dn4mYaNHHbc7wUDIkozHGkATA 
@listId = 1
@id = 8

# GET TodoItems
@pageNumber = 1
@pageSize = 10
GET https://localhost:44447/api/TodoItems?ListId={{listId}}&PageNumber={{pageNumber}}&PageSize={{pageSize}}
Authorization: Bearer {{AuthToken}}

###

# POST TodoItems
POST https://localhost:44447/api/TodoItems
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "listId": {{listId}},
  "title": "My todo item"
}


###

#POST TodoItems

PUT https://localhost:44447/api/TodoItems/{{id}}
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "id": {{id}},
  "title": "My edited todo item",
  "done": true
}

###

#DELETE TodoItems
DELETE https://localhost:44447/api/TodoItems/{{id}}
Authorization: Bearer {{AuthToken}}


###

#PUT TodoItems UpdateItemDetails
PUT https://localhost:44447/api/TodoItems/UpdateItemDetails?id={{id}}
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "id": {{id}},
  "listId": {{listId}},
  "priority": 0,
  "note": "My note"
}
